# Generated by Django 3.1.1 on 2020-11-01 03:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
