# Generated by Django 3.1.1 on 2020-11-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20201101_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='description',
            field=models.TextField(default='Add a description'),
            preserve_default=False,
        ),
    ]
