# Generated by Django 3.1.1 on 2020-11-29 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guides', '0004_auto_20201129_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='guides_colab', to=settings.AUTH_USER_MODEL),
        ),
    ]
